all:
  children:
    k8s:
      children:
        masters:
          hosts:
            192.168.0.71:
            192.168.0.72:
            192.168.0.73:
        workers:
          hosts:
            192.168.0.81:
            192.168.0.82:
            192.168.0.83:
        haproxy:
          hosts:
            192.168.0.70: